apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  annotations:
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/6STT4/TPBCHv8qrOSfdxGn+Su8FxGkFh4K4T+xxa+rYkT1pF6363VGipbS7UBY4JvYzfsb+zSMMxKiQEbpHQOc8Ixvv4vzp+y8kORKvgvEricyWVsbfGQUdTG5Ah1tS6YByZxxB8kvAHx2FdHvYQwd3hzz579449f9HkoH4t5jDgaADOUX2Q6rXZa3WSO26UK9C44hy4dMhje04xLoPcEpABlo6/WQGiozDCJ2brE3AYk926f+iXIQOrHHTAyQg7RSZwuoh3TdxXn368d00HqlalynGaLZuIMfFTyHvOHibjhbdTHGYbl3hDuMOOqgKSbnWWanzTJZUySYrSPQKkVReCy21rBVJAQmEPV3wr3F8RlwKpsHbC8vrncRS3dzwlJB0CY6gtchUkxeiLduasBB921AjsVdFLVpBTYVYCVHlum2yOitznZVlqVpdKKGbF8WPPuwpXJ1/SuBmai5zoS0Rp4o0TpZnMo4k59fvvefIAcclCt5ps92QXsZkNJ8pROMddM9kDjkksDdubnRz/+7NucbfG53O4flw4+2M0wEjh0nyFOjPRN8uSu/PY/wPppGRp3h1fRtC9RU6jTbSS88fa6fTtwAAAP//SP19UY0EAAA
    objectset.rio.cattle.io/id: unmanaged-machine
    objectset.rio.cattle.io/owner-gvk: /v1, Kind=Secret
    objectset.rio.cattle.io/owner-name: custom-f457d4ae943d
    objectset.rio.cattle.io/owner-namespace: c-m-s9pms7br
    pre-terminate.delete.hook.machine.cluster.x-k8s.io/rke-bootstrap-cleanup: rke-bootstrap-controller
  creationTimestamp: '2025-11-11T19:45:31Z'
  finalizers:
    - machine.cluster.x-k8s.io
  generation: 3
  labels:
    cattle.io/os: linux
    cluster.x-k8s.io/cluster-name: swe645-assignment3
    cluster.x-k8s.io/control-plane: 'true'
    objectset.rio.cattle.io/hash: 63ce1ff05f10c5e6c803e2bdaaed172fcfc7dec2
    rke.cattle.io/cluster-name: swe645-assignment3
    rke.cattle.io/control-plane-role: 'true'
    rke.cattle.io/etcd-role: 'true'
    rke.cattle.io/machine-id: 2e420d81329597ea32b98e8cabd37292e86aa62261f9807051f0555d9f3d2f8
    rke.cattle.io/worker-role: 'true'
  managedFields:
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:pre-terminate.delete.hook.machine.cluster.x-k8s.io/rke-bootstrap-cleanup: {}
          f:labels:
            .: {}
            f:cattle.io/os: {}
            f:cluster.x-k8s.io/cluster-name: {}
            f:cluster.x-k8s.io/control-plane: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/cluster-name: {}
            f:rke.cattle.io/control-plane-role: {}
            f:rke.cattle.io/etcd-role: {}
            f:rke.cattle.io/machine-id: {}
            f:rke.cattle.io/worker-role: {}
        f:spec:
          .: {}
          f:bootstrap:
            .: {}
            f:configRef: {}
          f:clusterName: {}
          f:infrastructureRef: {}
      manager: rancher
      operation: Update
      time: '2025-11-11T19:45:31Z'
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"machine.cluster.x-k8s.io": {}
          f:ownerReferences:
            .: {}
            k:{"uid":"6cd5d216-afad-4ded-9ada-85c298c9603f"}: {}
        f:spec:
          f:bootstrap:
            f:dataSecretName: {}
          f:providerID: {}
      manager: manager
      operation: Update
      time: '2025-11-11T19:47:58Z'
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:addresses: {}
          f:bootstrapReady: {}
          f:conditions: {}
          f:infrastructureReady: {}
          f:lastUpdated: {}
          f:nodeInfo:
            .: {}
            f:architecture: {}
            f:bootID: {}
            f:containerRuntimeVersion: {}
            f:kernelVersion: {}
            f:kubeProxyVersion: {}
            f:kubeletVersion: {}
            f:machineID: {}
            f:operatingSystem: {}
            f:osImage: {}
            f:systemUUID: {}
          f:nodeRef: {}
          f:observedGeneration: {}
          f:phase: {}
          f:v1beta2:
            .: {}
            f:conditions:
              .: {}
              k:{"type":"Available"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"BootstrapConfigReady"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"Deleting"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"InfrastructureReady"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"NodeHealthy"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"NodeReady"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"Paused"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"Ready"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
      manager: manager
      operation: Update
      subresource: status
      time: '2025-11-11T19:48:05Z'
  name: custom-f457d4ae943d
  namespace: fleet-default
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: swe645-assignment3
      uid: 6cd5d216-afad-4ded-9ada-85c298c9603f
  resourceVersion: '9709'
  uid: 37e13e95-e8dd-4fa3-89c5-d75e19737560
spec:
  bootstrap:
    configRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEBootstrap
      name: custom-f457d4ae943d
      namespace: fleet-default
    dataSecretName: custom-f457d4ae943d-machine-bootstrap
  clusterName: swe645-assignment3
  infrastructureRef:
    apiVersion: rke.cattle.io/v1
    kind: CustomMachine
    name: custom-f457d4ae943d
    namespace: fleet-default
  nodeDeletionTimeout: 10s
  providerID: rke2://ip-172-31-30-210
status:
  addresses:
    - address: 172.31.30.210
      type: InternalIP
    - address: ip-172-31-30-210
      type: Hostname
  bootstrapReady: true
  conditions:
    - lastTransitionTime: '2025-11-11T19:45:31Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2025-11-11T19:45:31Z'
      status: 'True'
      type: BootstrapReady
    - lastTransitionTime: '2025-11-11T19:45:31Z'
      status: 'True'
      type: InfrastructureReady
    - lastTransitionTime: '2025-11-11T19:48:05Z'
      status: 'True'
      type: NodeHealthy
    - lastTransitionTime: '2025-11-11T19:45:31Z'
      status: 'True'
      type: PlanApplied
    - lastTransitionTime: '2025-11-11T19:47:57Z'
      status: 'True'
      type: Reconciled
  infrastructureReady: true
  lastUpdated: '2025-11-11T19:48:05Z'
  nodeInfo:
    architecture: amd64
    bootID: 092705f4-51c5-4906-8de4-18d356f0756e
    containerRuntimeVersion: containerd://2.1.4-k3s2
    kernelVersion: 6.14.0-1015-aws
    kubeProxyVersion: ''
    kubeletVersion: v1.33.5+rke2r1
    machineID: ec28f1ed05ab6522d5337f4a8264908c
    operatingSystem: linux
    osImage: Ubuntu 24.04.3 LTS
    systemUUID: ec28f1ed-05ab-6522-d533-7f4a8264908c
  nodeRef:
    apiVersion: v1
    kind: Node
    name: ip-172-31-30-210
    uid: 521421ee-80be-4cd9-8447-11730f3435f8
  observedGeneration: 3
  phase: Running
  v1beta2:
    conditions:
      - lastTransitionTime: '2025-11-11T19:48:05Z'
        message: ''
        observedGeneration: 3
        reason: Available
        status: 'True'
        type: Available
      - lastTransitionTime: '2025-11-11T19:48:05Z'
        message: ''
        observedGeneration: 3
        reason: Ready
        status: 'True'
        type: Ready
      - lastTransitionTime: '2025-11-11T19:45:31Z'
        message: ''
        observedGeneration: 3
        reason: Ready
        status: 'True'
        type: BootstrapConfigReady
      - lastTransitionTime: '2025-11-11T19:45:31Z'
        message: ''
        observedGeneration: 3
        reason: Ready
        status: 'True'
        type: InfrastructureReady
      - lastTransitionTime: '2025-11-11T19:48:05Z'
        message: ''
        observedGeneration: 3
        reason: NodeHealthy
        status: 'True'
        type: NodeHealthy
      - lastTransitionTime: '2025-11-11T19:46:36Z'
        message: ''
        observedGeneration: 3
        reason: NodeReady
        status: 'True'
        type: NodeReady
      - lastTransitionTime: '2025-11-11T19:45:31Z'
        message: ''
        observedGeneration: 3
        reason: NotPaused
        status: 'False'
        type: Paused
      - lastTransitionTime: '2025-11-11T19:45:31Z'
        message: ''
        observedGeneration: 3
        reason: NotDeleting
        status: 'False'
        type: Deleting
