apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  annotations:
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/6STz3LTMBCHX4XZs526jv/InuECw6kDh8JwX0mrVIkseaR1W9rJuzP2lJC0EAocbelbfSv99hEGYtTICP0joPeBkW3waf4MckuKE/Eq2rBSyOxoZcOF1dDD5Af0uCGdD6hurCfIfguEO08x39zuoIeL28vszZX1+u1nUpH4j5jHgaAHNSUOQ152tdFd1RWVUK9C04hq4fMh3/LD9mFrGthnoCItnX6xAyXGYYTeT85l4FCSW/o/KpegB2f9dA8ZKDclpri6z3cizatPP36YpjtqqjrHlOzGD+R5/UsoeI7B5aNDP1Mcp3NXeIPpBnqoqOkq1bRSV1VtRCNIdVIWQqtL3SjSrShrUZRzpbijI/41js+IY8E8BndkebqTWOmzG54Ski/BWbdCt4UsCq3qujRyLVoSnSlqWSmBBuumXLdGCd2gELUhtW7bUlaiUbIxUr8ofhfijuLJ+fsMzqbmOBfGEXGuyeDkeCbTSGp+fRkCJ444LlEI3tjNNZllTEb7lWKywUP/TOb2EjLYWT83en314d2hxr8b7Q/h+XTm7aw3ERPHSfEU6e9E3y9KHw9j/B+miZGndHJ914T6G/QGXaKXnj/X9vvvAQAA//+OgzkijQQAAA
    objectset.rio.cattle.io/id: unmanaged-machine
    objectset.rio.cattle.io/owner-gvk: /v1, Kind=Secret
    objectset.rio.cattle.io/owner-name: custom-295fd949048c
    objectset.rio.cattle.io/owner-namespace: c-m-jtzjzjf6
    pre-terminate.delete.hook.machine.cluster.x-k8s.io/rke-bootstrap-cleanup: rke-bootstrap-controller
  creationTimestamp: '2025-11-11T01:56:56Z'
  finalizers:
    - machine.cluster.x-k8s.io
  generation: 3
  labels:
    cattle.io/os: linux
    cluster.x-k8s.io/cluster-name: swe645-assignment3
    cluster.x-k8s.io/control-plane: 'true'
    objectset.rio.cattle.io/hash: 4e694c67bd445f868ec9bb08dc1d6ced7825802e
    rke.cattle.io/cluster-name: swe645-assignment3
    rke.cattle.io/control-plane-role: 'true'
    rke.cattle.io/etcd-role: 'true'
    rke.cattle.io/machine-id: 378d70b00dc552fb387e89f05b4c8afa56237fc8d6a885fec3772b486cb6fbd
    rke.cattle.io/worker-role: 'true'
  managedFields:
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:pre-terminate.delete.hook.machine.cluster.x-k8s.io/rke-bootstrap-cleanup: {}
          f:labels:
            .: {}
            f:cattle.io/os: {}
            f:cluster.x-k8s.io/cluster-name: {}
            f:cluster.x-k8s.io/control-plane: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/cluster-name: {}
            f:rke.cattle.io/control-plane-role: {}
            f:rke.cattle.io/etcd-role: {}
            f:rke.cattle.io/machine-id: {}
            f:rke.cattle.io/worker-role: {}
        f:spec:
          .: {}
          f:bootstrap:
            .: {}
            f:configRef: {}
          f:clusterName: {}
          f:infrastructureRef: {}
      manager: rancher
      operation: Update
      time: '2025-11-11T01:56:56Z'
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"machine.cluster.x-k8s.io": {}
          f:ownerReferences:
            .: {}
            k:{"uid":"c29dd73b-b678-4d39-bcc4-588db238be5c"}: {}
        f:spec:
          f:bootstrap:
            f:dataSecretName: {}
          f:providerID: {}
      manager: manager
      operation: Update
      time: '2025-11-11T01:59:08Z'
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:addresses: {}
          f:bootstrapReady: {}
          f:infrastructureReady: {}
          f:lastUpdated: {}
          f:nodeInfo:
            .: {}
            f:architecture: {}
            f:bootID: {}
            f:containerRuntimeVersion: {}
            f:kernelVersion: {}
            f:kubeProxyVersion: {}
            f:kubeletVersion: {}
            f:machineID: {}
            f:operatingSystem: {}
            f:osImage: {}
            f:systemUUID: {}
          f:nodeRef: {}
          f:observedGeneration: {}
          f:phase: {}
          f:v1beta2:
            .: {}
            f:conditions:
              .: {}
              k:{"type":"Available"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"BootstrapConfigReady"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"Deleting"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"InfrastructureReady"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"NodeHealthy"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"NodeReady"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"Paused"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
              k:{"type":"Ready"}:
                .: {}
                f:lastTransitionTime: {}
                f:message: {}
                f:observedGeneration: {}
                f:reason: {}
                f:status: {}
                f:type: {}
      manager: manager
      operation: Update
      subresource: status
      time: '2025-11-11T01:59:30Z'
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2025-11-11T01:59:30Z'
  name: custom-295fd949048c
  namespace: fleet-default
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: swe645-assignment3
      uid: c29dd73b-b678-4d39-bcc4-588db238be5c
  resourceVersion: '7868'
  uid: 3498b91b-f700-4b71-ac23-2d60e7e7ae42
spec:
  bootstrap:
    configRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEBootstrap
      name: custom-295fd949048c
      namespace: fleet-default
    dataSecretName: custom-295fd949048c-machine-bootstrap
  clusterName: swe645-assignment3
  infrastructureRef:
    apiVersion: rke.cattle.io/v1
    kind: CustomMachine
    name: custom-295fd949048c
    namespace: fleet-default
  nodeDeletionTimeout: 10s
  providerID: rke2://ip-172-31-16-56
status:
  addresses:
    - address: 172.31.16.56
      type: InternalIP
    - address: ip-172-31-16-56
      type: Hostname
  bootstrapReady: true
  conditions:
    - lastTransitionTime: '2025-11-11T01:56:57Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2025-11-11T01:56:57Z'
      status: 'True'
      type: BootstrapReady
    - lastTransitionTime: '2025-11-11T01:56:57Z'
      status: 'True'
      type: InfrastructureReady
    - lastTransitionTime: '2025-11-11T01:59:18Z'
      status: 'True'
      type: NodeHealthy
    - lastTransitionTime: '2025-11-11T01:56:57Z'
      status: 'True'
      type: PlanApplied
    - lastTransitionTime: '2025-11-11T01:59:30Z'
      status: 'True'
      type: Reconciled
  infrastructureReady: true
  lastUpdated: '2025-11-11T01:59:18Z'
  nodeInfo:
    architecture: amd64
    bootID: 55bc8117-e563-4351-881b-0891e421743b
    containerRuntimeVersion: containerd://2.1.4-k3s2
    kernelVersion: 6.14.0-1015-aws
    kubeProxyVersion: ''
    kubeletVersion: v1.33.5+rke2r1
    machineID: ec2cfa85c40a224e49d67b14e3c3c26a
    operatingSystem: linux
    osImage: Ubuntu 24.04.3 LTS
    systemUUID: ec2cfa85-c40a-224e-49d6-7b14e3c3c26a
  nodeRef:
    apiVersion: v1
    kind: Node
    name: ip-172-31-16-56
    uid: e5633a96-89ab-43b3-83bc-2eb1189b34a9
  observedGeneration: 3
  phase: Running
  v1beta2:
    conditions:
      - lastTransitionTime: '2025-11-11T01:59:30Z'
        message: ''
        observedGeneration: 3
        reason: Available
        status: 'True'
        type: Available
      - lastTransitionTime: '2025-11-11T01:59:30Z'
        message: ''
        observedGeneration: 3
        reason: Ready
        status: 'True'
        type: Ready
      - lastTransitionTime: '2025-11-11T01:56:57Z'
        message: ''
        observedGeneration: 3
        reason: Ready
        status: 'True'
        type: BootstrapConfigReady
      - lastTransitionTime: '2025-11-11T01:56:57Z'
        message: ''
        observedGeneration: 3
        reason: Ready
        status: 'True'
        type: InfrastructureReady
      - lastTransitionTime: '2025-11-11T01:59:30Z'
        message: ''
        observedGeneration: 3
        reason: NodeHealthy
        status: 'True'
        type: NodeHealthy
      - lastTransitionTime: '2025-11-11T01:57:53Z'
        message: ''
        observedGeneration: 3
        reason: NodeReady
        status: 'True'
        type: NodeReady
      - lastTransitionTime: '2025-11-11T01:56:56Z'
        message: ''
        observedGeneration: 3
        reason: NotPaused
        status: 'False'
        type: Paused
      - lastTransitionTime: '2025-11-11T01:56:57Z'
        message: ''
        observedGeneration: 3
        reason: NotDeleting
        status: 'False'
        type: Deleting
