apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-backend
  labels:
    app: survey-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-backend
  template:
    metadata:
      labels:
        app: survey-backend
    spec:
      containers:
      - name: backend
        image: neerajreddy22/swe645-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_PATH
          value: "/data/survey.db"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 30
        volumeMounts:
        - name: survey-data
          mountPath: /data
      volumes:
      - name: survey-data
        persistentVolumeClaim:
          claimName: survey-pvc
