apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-backend
  labels:
    app: survey-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-backend
  template:
    metadata:
      labels:
        app: survey-backend
    spec:
      containers:
      - name: backend
        image: neerajreddy22/swe645-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "100.30.1.131"        
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "survey_user"
        - name: DB_PASSWORD
          value: "Surajneeraj1"     # ‚ùó FIXED (no space)
        - name: DB_NAME
          value: "survey"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 30
