apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-backend
  template:
    metadata:
      labels:
        app: survey-backend
    spec:
      containers:
      - name: backend
        image: neerajreddy22/swe645-backend:latest
        imagePullPolicy: Always
        env:
        - name: DB_PATH
          value: "/tmp/survey.db"
        ports:
        - containerPort: 8000
