apiVersion: v1
kind: Service
metadata:
  name: survey-frontend
  labels:
    app: survey-frontend
spec:
  selector:
    app: survey-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31000   # you can choose any port between 30000â€“32767
  type: NodePort
