apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-frontend
  template:
    metadata:
      labels:
        app: survey-frontend
    spec:
      containers:
      - name: frontend
        image: neerajreddy22/swe645-frontend:latest
        ports:
        - containerPort: 80
