apiVersion: v1
kind: Service
metadata:
  name: survey-frontend
  labels:
    app: survey-frontend
spec:
  selector:
    app: survey-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort